### ISSUE TITLE
Gevent depends on Cython on Mac OS X

### ISSUE THREAD

**Issue by kevinburke** [twilio/shadow#2]
Trying to install this on my Snow Leopard laptop. I created a new virtualenv, then ran:

``` bash
python setup.py install
```

and got the following error:

``` python
sh: cython: command not found
Traceback (most recent call last):
  File "util/cythonpp.py", line 801, in <module>
    process_filename(filename, options.output_file)
  File "util/cythonpp.py", line 85, in process_filename
    output = run_cython(pyx_filename, sourcehash, output_filename, banner, comment)
  File "util/cythonpp.py", line 529, in run_cython
    system(command, comment)
  File "util/cythonpp.py", line 539, in system
    raise AssertionError('%r failed with code %s' % (command, result))
AssertionError: 'cython -o gevent.core.c gevent/core.pyx' failed with code 32512
```

Running `pip install cython`, then running `python setup.py install` worked. I'm not sure why exactly Cython is needed, but you may want to add Cython as a dependency.

**Comment by kevinburke** [comment]
Looking at setup.py, it looks like Cython is listed as a dependency.

**Comment by kelvl** [comment]
yes it should install properly when u do a python setup.py install or a pip install .

**Comment by kevinburke** [comment]
It didn't work for me even with the dependency - I'd suggest trying to python setup.py in a virtualenv, without Cython in your path. It looks like I am not the only one running into issues: https://twitter.com/BrianMMcClain/status/259384481222361088

**Comment by kelvl** [comment]
could it be because of `cython` vs `Cython`? 

I am on mountain lion and just doing `pip install .` on a brand new virtualenv --no-site-packages works for me

**Comment by jpf** [comment]
I was able to resolve this issue by changing the ordering of the requirements in setup.py, I have a pull request which addresses this.
