### ISSUE TITLE
Shadow should set Host headers for the servers it's proxying to?

### ISSUE THREAD

**Issue by jpf** [twilio/shadow#4]
I'm using shadow to help me verify that the code I'm running on a new heroku stack (cedar v. aspen) is working as expected.

I ran into an issue where I got this back from shadow: "Heroku | No such app [etc]". This appears to be due to heroku routing based on Host headers.

**Comment by kyleconroy** [comment]
Shadow should forward all headers along with the request if it's not already doing it.

**Comment by kelvl** [comment]
Shadow should be forwarding all headers verbatim. Custom headers for each downstream server can be set in the configuration file. 

This test should validate that headers are being forwarded: https://github.com/twilio/shadow/blob/master/tests/unit/test_proxy_flask.py#L246

**Comment by jpf** [comment]
Okay, got the custom header forwarding working, thanks!
